name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:     # Allows manual trigger from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Updated to latest version for better compatibility

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Nayanthi-Weerasuriya 
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark  # Optional: Adds a dark mode variant

      - name: Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update contribution snake"
          add: "dist/*.svg"  # Updated to include all generated SVGs
